=begin
#QuantiModo

#QuantiModo makes it easy to retrieve normalized user data from a wide array of devices and applications. [Learn about QuantiModo](https://quantimo.do), check out our [docs](https://github.com/QuantiModo/docs) or contact us at [help.quantimo.do](https://help.quantimo.do). 

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CorrelationsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CorrelationsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CorrelationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CorrelationsApi' do
    it 'should create an instact of CorrelationsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CorrelationsApi)
    end
  end

  # unit tests for v1_aggregated_correlations_get
  # Get aggregated correlations
  # Get correlations based on the anonymized aggregate data from all QuantiModo users.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_token User&#39;s OAuth2 access token
  # @option opts [Integer] :user_id User&#39;s id
  # @option opts [String] :effect Variable name of the effect variable for which the user desires correlations
  # @option opts [String] :cause Variable name of the cause variable for which the user desires correlations
  # @option opts [String] :correlation_coefficient Pearson correlation coefficient between cause and effect after lagging by onset delay and grouping by duration of action
  # @option opts [String] :onset_delay The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
  # @option opts [String] :duration_of_action The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
  # @option opts [String] :updated_at The time that this measurement was last updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot;.  Generally, you&#39;ll be retrieving new or updated user data. To avoid unnecessary API calls, you&#39;ll want to store your last refresh time locally. Then whenever you make a request to get new data, you should limit the returned results to those updated since your last refresh by appending append &#x60;?updatedAt&#x3D;(ge)2013-01-D01T01:01:01 to your request.
  # @option opts [Integer] :limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0.
  # @option opts [Integer] :offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;.
  # @option opts [Integer] :sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order.
  # @option opts [BOOLEAN] :outcomes_of_interest Only include correlations for which the effect is an outcome of interest for the user
  # @return [Array<Correlation>]
  describe 'v1_aggregated_correlations_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_aggregated_correlations_post
  # Store or Update a Correlation
  # Add correlation
  # @param body Provides correlation data
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_token User&#39;s OAuth2 access token
  # @option opts [Integer] :user_id User&#39;s id
  # @return [nil]
  describe 'v1_aggregated_correlations_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_correlations_get
  # Get correlations
  # Get correlations based on data from a single user.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_token User&#39;s OAuth2 access token
  # @option opts [Integer] :user_id User&#39;s id
  # @option opts [String] :effect Variable name of the effect variable for which the user desires correlations
  # @option opts [String] :cause Variable name of the cause variable for which the user desires correlations
  # @option opts [String] :correlation_coefficient Pearson correlation coefficient between cause and effect after lagging by onset delay and grouping by duration of action
  # @option opts [String] :onset_delay The amount of time in seconds that elapses after the predictor/stimulus event before the outcome as perceived by a self-tracker is known as the “onset delay”. For example, the “onset delay” between the time a person takes an aspirin (predictor/stimulus event) and the time a person perceives a change in their headache severity (outcome) is approximately 30 minutes.
  # @option opts [String] :duration_of_action The amount of time over which a predictor/stimulus event can exert an observable influence on an outcome variable’s value. For instance, aspirin (stimulus/predictor) typically decreases headache severity for approximately four hours (duration of action) following the onset delay.
  # @option opts [String] :updated_at The time that this measurement was last updated in the UTC format \&quot;YYYY-MM-DDThh:mm:ss\&quot;.  Generally, you&#39;ll be retrieving new or updated user data. To avoid unnecessary API calls, you&#39;ll want to store your last refresh time locally. Then whenever you make a request to get new data, you should limit the returned results to those updated since your last refresh by appending append &#x60;?updatedAt&#x3D;(ge)2013-01-D01T01:01:01 to your request.
  # @option opts [Integer] :limit The LIMIT is used to limit the number of results returned. So if you have 1000 results, but only want to the first 10, you would set this to 10 and offset to 0.
  # @option opts [Integer] :offset Since the maximum limit is 200 records, to get more than that you&#39;ll have to make multiple API calls and page through the results. To retrieve all the data, you can iterate through data by using the &#x60;limit&#x60; and &#x60;offset&#x60; query parameters.  For example, if you want to retrieve data from 61-80 then you can use a query with the following parameters, &#x60;imit&#x3D;20&amp;offset&#x3D;60&#x60;.
  # @option opts [Integer] :sort Sort by given field. If the field is prefixed with &#x60;-, it will sort in descending order.
  # @option opts [BOOLEAN] :outcomes_of_interest Only include correlations for which the effect is an outcome of interest for the user
  # @return [Array<Correlation>]
  describe 'v1_correlations_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_organizations_organization_id_users_user_id_variables_variable_name_causes_get
  # Search user correlations for a given cause
  # Returns average of all correlations and votes for all user cause variables for a given cause. If parameter \&quot;include_public\&quot; is used, it also returns public correlations. User correlation overwrites or supersedes public correlation.
  # @param organization_id Organization ID
  # @param user_id2 User id
  # @param variable_name Effect variable name
  # @param organization_token Organization access token
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_token User&#39;s OAuth2 access token
  # @option opts [Integer] :user_id User&#39;s id
  # @option opts [String] :include_public Include public correlations, Can be \&quot;1\&quot; or empty.
  # @return [Array<Correlation>]
  describe 'v1_organizations_organization_id_users_user_id_variables_variable_name_causes_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_organizations_organization_id_users_user_id_variables_variable_name_effects_get
  # Search user correlations for a given cause
  # Returns average of all correlations and votes for all user cause variables for a given effect. If parameter \&quot;include_public\&quot; is used, it also returns public correlations. User correlation overwrites or supersedes public correlation.
  # @param organization_id Organization ID
  # @param user_id2 User id
  # @param variable_name Cause variable name
  # @param organization_token Organization access token
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_token User&#39;s OAuth2 access token
  # @option opts [Integer] :user_id User&#39;s id
  # @option opts [String] :include_public Include public correlations, Can be \&quot;1\&quot; or empty.
  # @return [Array<CommonResponse>]
  describe 'v1_organizations_organization_id_users_user_id_variables_variable_name_effects_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_public_correlations_search_search_get
  # Get average correlations for variables containing search term
  # Returns the average correlations from all users for all public variables that contain the characters in the search query. Returns average of all users public variable correlations with a specified cause or effect.
  # @param search Name of the variable that you want to know the causes or effects of.
  # @param effect_or_cause Setting this to effect indicates that the searched variable is the effect and that the causes of this variable should be returned. cause indicates that the searched variable is the cause and the effects should be returned.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_token User&#39;s OAuth2 access token
  # @option opts [Integer] :user_id User&#39;s id
  # @option opts [BOOLEAN] :outcomes_of_interest Only include correlations for which the effect is an outcome of interest for the user
  # @return [Array<Correlation>]
  describe 'v1_public_correlations_search_search_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_variables_variable_name_causes_get
  # Search user correlations for a given effect
  # Returns average of all correlations and votes for all user cause variables for a given effect
  # @param variable_name Effect variable name
  # @param [Hash] opts the optional parameters
  # @return [Array<Correlation>]
  describe 'v1_variables_variable_name_causes_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_variables_variable_name_effects_get
  # Search user correlations for a given cause
  # Returns average of all correlations and votes for all user effect variables for a given cause
  # @param variable_name Cause variable name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_token User&#39;s OAuth2 access token
  # @option opts [Integer] :user_id User&#39;s id
  # @option opts [String] :correlation_coefficient You can use this to get effects with correlations greater than or less than 0
  # @return [Array<Correlation>]
  describe 'v1_variables_variable_name_effects_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_variables_variable_name_public_causes_get
  # Search public correlations for a given effect
  # Returns average of all correlations and votes for all public cause variables for a given effect
  # @param variable_name Effect variable name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_token User&#39;s OAuth2 access token
  # @option opts [Integer] :user_id User&#39;s id
  # @option opts [String] :correlation_coefficient You can use this to get causes with correlations greater than or less than 0
  # @return [Array<Correlation>]
  describe 'v1_variables_variable_name_public_causes_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_variables_variable_name_public_effects_get
  # Search public correlations for a given cause
  # Returns average of all correlations and votes for all public cause variables for a given cause
  # @param variable_name Cause variable name
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_token User&#39;s OAuth2 access token
  # @option opts [Integer] :user_id User&#39;s id
  # @return [Array<Correlation>]
  describe 'v1_variables_variable_name_public_effects_get test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_votes_delete_post
  # Delete vote
  # Delete previously posted vote
  # @param body The cause and effect variable names for the predictor vote to be deleted.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_token User&#39;s OAuth2 access token
  # @option opts [Integer] :user_id User&#39;s id
  # @return [CommonResponse]
  describe 'v1_votes_delete_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for v1_votes_post
  # Post or update vote
  # This is to enable users to indicate their opinion on the plausibility of a causal relationship between a treatment and outcome. QuantiModo incorporates crowd-sourced plausibility estimations into their algorithm. This is done allowing user to indicate their view of the plausibility of each relationship with thumbs up/down buttons placed next to each prediction.
  # @param body Contains the cause variable, effect variable, and vote value.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :access_token User&#39;s OAuth2 access token
  # @option opts [Integer] :user_id User&#39;s id
  # @return [CommonResponse]
  describe 'v1_votes_post test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
